name: Build LIB

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build.yml
      - filepicker/**
      - components/**
      - components-compose/**
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
  pull_request:
    paths:
      - .github/workflows/build.yml
      - filepicker/**
      - components/**
      - components-compose/**
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts

jobs:
  build:
    name: Build release apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.5.0

      - name: Build with gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleRelease